default_context:
  project_name: 'site'
  project_slug: 'fisher-planet-blog'
  domain_main: 'fisherpla.net'
  domain_staging: 'stage.fisherpla.net'
  docker_swarm_stack_name_main: 'fisher-planet'
  docker_swarm_stack_name_staging: 'stage-fisher-planet'
  secret_key: 'thisisnotasecretatalldonotusethisorelseIwillslappyamuddah'
  first_superuser: 'admin@fisherpla.net'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fisherpla.net", "https://stage.fisherpla.net", "https://fisherpla.net", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fisherpla.net'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@fisherpla.net'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'fisher-planet'
  traefik_constraint_tag_staging: 'stage-fisher-planet'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
